### ISSUE TITLE
Not support Python3.X?

### ISSUE THREAD

**Issue by gVimer** [Aborres/vim-everything#1]
When I use call VE()   there has errors
![image](https://user-images.githubusercontent.com/6241431/103471756-dce43380-4dbe-11eb-828c-4e4da724456f.png)

**Comment by gVimer** [comment]
Can support C-j/C-k to move betweenthe results in input_mode?

**Comment by Aborres** [comment]
Hi there,

I understand you managed to fix the issue with python? (Looking at your second comment)

I will add support for C-j/C-k, I will update the thread whenever that is done.

**Comment by gVimer** [comment]
No . I chang Py3.x to Py2.X ,then it's works!

**Comment by gVimer** [comment]
Can you decorate the pop-up window a little more beautifully? eg:
![image](https://user-images.githubusercontent.com/6241431/103476749-66adf400-4df3-11eb-9a93-1e72ba32f3d5.png)



or make the plugin an extension of  Leaderf which A very powerful search plugin
eg:https://github.com/voldikss/LeaderF-everything  
But this plugin uses es.exe It's not good to use everything.dll directly

**Comment by gVimer** [comment]
I'm trying to make the plugin to be an extension of Leaderf

**Comment by Aborres** [comment]
I have updated the plugging to support both python2 and python 3 (see: https://github.com/Aborres/vim-everything/commit/d7062e56b06b3b4d4dfaee89f1ac5fac21b43b17) 

About the UI, LeaderF was written before 8.2 (so it doesn't make use of the native vim floating windows), I do agree LeaderF is prettier but I have no intention of writing a new piece of UI from scratch so I will stick to the native floating windows.
